### ISSUE TITLE
panic! occurs after OS starts

### ISSUE THREAD

**Issue by ekicyou** [hyperium/hyper#1215]
The problem that occurs with the master branch.
If you run the communication within 1.5 minutes after the OS starts, a panic! will occur. Windows/iOS has a problem.

stack trace.

```
thread '<unnamed>' panicked at 'overflow when subtracting duration from time', src\libcore\option.rs:794
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:354
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:371
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:549
   4: std::panicking::begin_panic<collections::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:511
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:495
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:471
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:69
   8: core::option::expect_failed
             at C:\projects\rust\src\libcore\option.rs:794
   9: std::time::{{impl}}::sub
             at C:\projects\rust\src\libstd\time\mod.rs:234
  10: hyper::client::pool::{{impl}}::new::{{closure}}
             at c:\rust\cargo\git\checkouts\hyper-817b53a166fc1c58\5d19ef8\src\client\pool.rs:267
  11: core::option::Option<std::time::duration::Duration>::map<std::time::duration::Duration,std::time::Instant,closure>
             at C:\projects\rust\src\libcore\option.rs:392
  12: hyper::client::pool::Expiration::new
             at c:\rust\cargo\git\checkouts\hyper-817b53a166fc1c58\5d19ef8\src\client\pool.rs:267
  13: hyper::client::pool::{{impl}}::poll<tokio_proto::util::client_proxy::ClientProxy<tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RequestLine>, hyper::http::body::Body>, tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RawStatus>, tokio_proto::streaming::body::Body<hyper::http::chunk::Chunk, hyper::error::Error>>, hyper::error::Error>>
             at c:\rust\cargo\git\checkouts\hyper-817b53a166fc1c58\5d19ef8\src\client\pool.rs:219
  14: futures::future::select::{{impl}}::poll<hyper::client::pool::Checkout<tokio_proto::util::client_proxy::ClientProxy<tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RequestLine>, hyper::http::body::Body>, tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RawStatus>, tokio_proto::streaming::body::Body<hyper::http::chunk::Chunk, hyper::error::Error>>, hyper::error::Error>>,futures::future::map::Map<hyper::client::connect::HttpConnecting, closure>>
             at c:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.14\src\future\select.rs:48
  15: futures::future::map::{{impl}}::poll<hyper::client::pool::Pooled<tokio_proto::util::client_proxy::ClientProxy<tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RequestLine>, hyper::http::body::Body>, tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RawStatus>, tokio_proto::streaming::body::Body<hyper::http::chunk::Chunk, hyper::error::Error>>, hyper::error::Error>>,futures::future::select::Select<hyper::client::pool::Checkout<tokio_proto::util::client_proxy::ClientProxy<tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RequestLine>, hyper::http::body::Body>, tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RawStatus>, tokio_proto::streaming::body::Body<hyper::http::chunk::Chunk, hyper::error::Error>>, hyper::error::Error>>, futures::future::map::Map<hyper::client::connect::HttpConnecting, closure>>,closure>
             at c:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.14\src\future\map.rs:30
  16: futures::future::map_err::{{impl}}::poll<hyper::error::Error,futures::future::map::Map<futures::future::select::Select<hyper::client::pool::Checkout<tokio_proto::util::client_proxy::ClientProxy<tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RequestLine>, hyper::http::body::Body>, tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RawStatus>, tokio_proto::streaming::body::Body<hyper::http::chunk::Chunk, hyper::error::Error>>, hyper::error::Error>>, futures::future::map::Map<hyper::client::connect::HttpConnecting, closure>>, closure>,closure>
             at c:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.14\src\future\map_err.rs:30
  17: futures::future::chain::Chain<futures::future::map_err::MapErr<futures::future::map::Map<futures::future::select::Select<hyper::client::pool::Checkout<tokio_proto::util::client_proxy::ClientProxy<tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RequestLine>, hyper::http::body::Body>, tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RawStatus>, tokio_proto::streaming::body::Body<hyper::http::chunk::Chunk, hyper::error::Error>>, hyper::error::Error>>, futures::future::map::Map<hyper::client::connect::HttpConnecting, closure>>, closure>, closure>, tokio_proto::util::client_proxy::Response<tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RawStatus>, tokio_proto::streaming::body::Body<hyper::http::chunk::Chunk, hyper::error::Error>>, hyper::error::Error>, closure>::poll<futures::future::map_err::MapErr<futures::future::map::Map<futures::future::select::Select<hyper::client::pool::Checkout<tokio_proto::util::client_proxy::ClientProxy<tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RequestLine>, hyper::http::body::Body>, tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RawStatus>, tokio_proto::streaming::body::Body<hyper::http::chunk::Chunk, hyper::error::Error>>, hyper::error::Error>>, futures::future::map::Map<hyper::client::connect::HttpConnecting, closure>>, closure>, closure>,tokio_proto::util::client_proxy::Response<tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RawStatus>, tokio_proto::streaming::body::Body<hyper::http::chunk::Chunk, hyper::error::Error>>, hyper::error::Error>,closure,closure>
             at c:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.14\src\future\chain.rs:26
  18: futures::future::and_then::{{impl}}::poll<futures::future::map_err::MapErr<futures::future::map::Map<futures::future::select::Select<hyper::client::pool::Checkout<tokio_proto::util::client_proxy::ClientProxy<tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RequestLine>, hyper::http::body::Body>, tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RawStatus>, tokio_proto::streaming::body::Body<hyper::http::chunk::Chunk, hyper::error::Error>>, hyper::error::Error>>, futures::future::map::Map<hyper::client::connect::HttpConnecting, closure>>, closure>, closure>,tokio_proto::util::client_proxy::Response<tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RawStatus>, tokio_proto::streaming::body::Body<hyper::http::chunk::Chunk, hyper::error::Error>>, hyper::error::Error>,closure>
             at c:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.14\src\future\and_then.rs:32
  19: futures::future::map::{{impl}}::poll<hyper::http::response::Response<hyper::http::body::Body>,futures::future::and_then::AndThen<futures::future::map_err::MapErr<futures::future::map::Map<futures::future::select::Select<hyper::client::pool::Checkout<tokio_proto::util::client_proxy::ClientProxy<tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RequestLine>, hyper::http::body::Body>, tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RawStatus>, tokio_proto::streaming::body::Body<hyper::http::chunk::Chunk, hyper::error::Error>>, hyper::error::Error>>, futures::future::map::Map<hyper::client::connect::HttpConnecting, closure>>, closure>, closure>, tokio_proto::util::client_proxy::Response<tokio_proto::streaming::message::Message<hyper::http::MessageHead<hyper::http::RawStatus>, tokio_proto::streaming::body::Body<hyper::http::chunk::Chunk, hyper::error::Error>>, hyper::error::Error>, closure>,closure>
             at c:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.14\src\future\map.rs:30
  20: futures::future::{{impl}}::poll<Future>
             at c:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.14\src\future\mod.rs:107
  21: hyper::client::{{impl}}::poll
             at c:\rust\cargo\git\checkouts\hyper-817b53a166fc1c58\5d19ef8\src\client\mod.rs:126
  22: futures::future::chain::Chain<hyper::client::FutureResponse, futures::stream::fold::Fold<hyper::http::body::Body, closure, core::result::Result<collections::vec::Vec<u8>, hyper::error::Error>, collections::vec::Vec<u8>>, closure>::poll<hyper::client::FutureResponse,futures::stream::fold::Fold<hyper::http::body::Body, closure, core::result::Result<collections::vec::Vec<u8>, hyper::error::Error>, collections::vec::Vec<u8>>,closure,closure>
             at c:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.14\src\future\chain.rs:26
  23: futures::future::and_then::{{impl}}::poll<hyper::client::FutureResponse,futures::stream::fold::Fold<hyper::http::body::Body, closure, core::result::Result<collections::vec::Vec<u8>, hyper::error::Error>, collections::vec::Vec<u8>>,closure>
             at c:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.14\src\future\and_then.rs:32
  24: futures::future::select2::{{impl}}::poll<futures::future::and_then::AndThen<hyper::client::FutureResponse, futures::stream::fold::Fold<hyper::http::body::Body, closure, core::result::Result<collections::vec::Vec<u8>, hyper::error::Error>, collections::vec::Vec<u8>>, closure>,tokio_core::reactor::timeout::Timeout>
             at c:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.14\src\future\select2.rs:24
  25: futures::task_impl::{{impl}}::poll_future_notify::{{closure}}<futures::future::select2::Select2<futures::future::and_then::AndThen<hyper::client::FutureResponse, futures::stream::fold::Fold<hyper::http::body::Body, closure, core::result::Result<collections::vec::Vec<u8>, hyper::error::Error>, collections::vec::Vec<u8>>, closure>, tokio_core::reactor::timeout::Timeout>,alloc::arc::Arc<tokio_core::reactor::MySetReadiness>>
             at c:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.14\src\task_impl\mod.rs:291
  26: futures::task_impl::{{impl}}::enter::{{closure}}<futures::future::select2::Select2<futures::future::and_then::AndThen<hyper::client::FutureResponse, futures::stream::fold::Fold<hyper::http::body::Body, closure, core::result::Result<collections::vec::Vec<u8>, hyper::error::Error>, collections::vec::Vec<u8>>, closure>, tokio_core::reactor::timeout::Timeout>,closure,core::result::Result<futures::poll::Async<futures::future::either::Either<(collections::vec::Vec<u8>, tokio_core::reactor::timeout::Timeout), ((), futures::future::and_then::AndThen<hyper::client::FutureResponse, futures::stream::fold::Fold<hyper::http::body::Body, closure, core::result::Result<collections::vec::Vec<u8>, hyper::error::Error>, collections::vec::Vec<u8>>, closure>)>>, futures::future::either::Either<(hyper::error::Error, tokio_core::reactor::timeout::Timeout), (std::io::error::Error, futures::future::and_then::AndThen<hyper::client::FutureResponse, futures::stream::fold::Fold<hyper::http::body::Body, closure, core::result::Result<collections::vec::Vec<u8>, hyper::error::Error>, collections::vec::Vec<u8>>, closure>)>>>
             at c:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.14\src\task_impl\mod.rs:352
  27: futures::task_impl::std::set<closure,core::result::Result<futures::poll::Async<futures::future::either::Either<(collections::vec::Vec<u8>, tokio_core::reactor::timeout::Timeout), ((), futures::future::and_then::AndThen<hyper::client::FutureResponse, futures::stream::fold::Fold<hyper::http::body::Body, closure, core::result::Result<collections::vec::Vec<u8>, hyper::error::Error>, collections::vec::Vec<u8>>, closure>)>>, futures::future::either::Either<(hyper::error::Error, tokio_core::reactor::timeout::Timeout), (std::io::error::Error, futures::future::and_then::AndThen<hyper::client::FutureResponse, futures::stream::fold::Fold<hyper::http::body::Body, closure, core::result::Result<collections::vec::Vec<u8>, hyper::error::Error>, collections::vec::Vec<u8>>, closure>)>>>
             at c:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.14\src\task_impl\std\mod.rs:90
  28: futures::task_impl::Spawn<futures::future::select2::Select2<futures::future::and_then::AndThen<hyper::client::FutureResponse, futures::stream::fold::Fold<hyper::http::body::Body, closure, core::result::Result<collections::vec::Vec<u8>, hyper::error::Error>, collections::vec::Vec<u8>>, closure>, tokio_core::reactor::timeout::Timeout>>::enter<futures::future::select2::Select2<futures::future::and_then::AndThen<hyper::client::FutureResponse, futures::stream::fold::Fold<hyper::http::body::Body, closure, core::result::Result<collections::vec::Vec<u8>, hyper::error::Error>, collections::vec::Vec<u8>>, closure>, tokio_core::reactor::timeout::Timeout>,closure,core::result::Result<futures::poll::Async<futures::future::either::Either<(collections::vec::Vec<u8>, tokio_core::reactor::timeout::Timeout), ((), futures::future::and_then::AndThen<hyper::client::FutureResponse, futures::stream::fold::Fold<hyper::http::body::Body, closure, core::result::Result<collections::vec::Vec<u8>, hyper::error::Error>, collections::vec::Vec<u8>>, closure>)>>, futures::future::either::Either<(hyper::error::Error, tokio_core::reactor::timeout::Timeout), (std::io::error::Error, futures::future::and_then::AndThen<hyper::client::FutureResponse, futures::stream::fold::Fold<hyper::http::body::Body, closure, core::result::Result<collections::vec::Vec<u8>, hyper::error::Error>, collections::vec::Vec<u8>>, closure>)>>>
             at c:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.14\src\task_impl\mod.rs:352
  29: futures::task_impl::Spawn<futures::future::select2::Select2<futures::future::and_then::AndThen<hyper::client::FutureResponse, futures::stream::fold::Fold<hyper::http::body::Body, closure, core::result::Result<collections::vec::Vec<u8>, hyper::error::Error>, collections::vec::Vec<u8>>, closure>, tokio_core::reactor::timeout::Timeout>>::poll_future_notify<futures::future::select2::Select2<futures::future::and_then::AndThen<hyper::client::FutureResponse, futures::stream::fold::Fold<hyper::http::body::Body, closure, core::result::Result<collections::vec::Vec<u8>, hyper::error::Error>, collections::vec::Vec<u8>>, closure>, tokio_core::reactor::timeout::Timeout>,alloc::arc::Arc<tokio_core::reactor::MySetReadiness>>
             at c:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.14\src\task_impl\mod.rs:291
  30: tokio_core::reactor::{{impl}}::run::{{closure}}<futures::future::select2::Select2<futures::future::and_then::AndThen<hyper::client::FutureResponse, futures::stream::fold::Fold<hyper::http::body::Body, closure, core::result::Result<collections::vec::Vec<u8>, hyper::error::Error>, collections::vec::Vec<u8>>, closure>, tokio_core::reactor::timeout::Timeout>>
             at c:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\tokio-core-0.1.8\src\reactor\mod.rs:235
  31: scoped_tls::ScopedKey<tokio_core::reactor::Core>::set<tokio_core::reactor::Core,closure,core::result::Result<futures::poll::Async<futures::future::either::Either<(collections::vec::Vec<u8>, tokio_core::reactor::timeout::Timeout), ((), futures::future::and_then::AndThen<hyper::client::FutureResponse, futures::stream::fold::Fold<hyper::http::body::Body, closure, core::result::Result<collections::vec::Vec<u8>, hyper::error::Error>, collections::vec::Vec<u8>>, closure>)>>, futures::future::either::Either<(hyper::error::Error, tokio_core::reactor::timeout::Timeout), (std::io::error::Error, futures::future::and_then::AndThen<hyper::client::FutureResponse, futures::stream::fold::Fold<hyper::http::body::Body, closure, core::result::Result<collections::vec::Vec<u8>, hyper::error::Error>, collections::vec::Vec<u8>>, closure>)>>>
             at c:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\scoped-tls-0.1.0\src\lib.rs:135
  32: tokio_core::reactor::Core::run<futures::future::select2::Select2<futures::future::and_then::AndThen<hyper::client::FutureResponse, futures::stream::fold::Fold<hyper::http::body::Body, closure, core::result::Result<collections::vec::Vec<u8>, hyper::error::Error>, collections::vec::Vec<u8>>, closure>, tokio_core::reactor::timeout::Timeout>>
             at c:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\tokio-core-0.1.8\src\reactor\mod.rs:234
  33: pub130_hyper::Client::post_json
             at <unknown>:76
  34: pub130::async_client::runtime::Runtime::request_impl
             at <unknown>:65
  35: pub130::async_client::runtime::Runtime::request
             at <unknown>:28
  36: pub130::api::request
             at <unknown>:80
  37: pub130::request
             at <unknown>:102
  38: <unknown>
  39: <unknown>
  40: <unknown>
  41: <unknown>
  42: <unknown>
  43: <unknown>
  44: <unknown>
  45: LegacyNGenTryEnumerateFusionCache
  46: <unknown>
```

Is there a problem with the duration or instant treatment?

**Comment by seanmonstar** [comment]
The code that's panicking is essentially this:

```rust
let expiration = Instant::now() - pool.timeout; // panic!
pool.find_conn_where_idle_instant_is_later_than(expiration)
```

Looking in the [docs](https://doc.rust-lang.org/std/time/struct.Instant.html), there doesn't seem to be a way to do a saturating (or even checked) subtraction. And without a constant signifying "0", I'm not even sure of some way to check that `Instant::now() - ZERO > timeout`...

**Comment by seanmonstar** [comment]
This could be done differently, by saying for every socket, `if Instant::now().elapsed(conn.idle) > timeout`, but that requires doing subtraction operations for every socket. I had hoped to do the subtraction and clock check only once, and then only do a `cmp` check for each socket...

**Comment by ekicyou** [comment]
I confirmed a good operation. Thank you!
