### ISSUE TITLE
'dispatch dropped without returning error' panic with no-proto

### ISSUE THREAD

**Issue by sfackler** [hyperium/hyper#1388]
```rust
extern crate hyper;
extern crate tokio_core;
extern crate tokio_io;
extern crate futures;

use tokio_core::reactor::{Core, Timeout};
use tokio_core::net::TcpStream;
use tokio_io::{AsyncRead, AsyncWrite};
use hyper::{Client, Uri};
use hyper::client::HttpConnector;
use hyper::server::Service;
use std::time::Duration;
use std::cell::Cell;
use futures::{Future, Stream, stream, future};
use std::io::{self, Read, Write};
use std::net::TcpListener;
use std::thread;

fn main() {
    let mut core = Core::new().unwrap();
    let handle = core.handle();

    let listener = TcpListener::bind("127.0.0.1:0").unwrap();
    let addr = listener.local_addr().unwrap();

    thread::spawn(move || {
        for sock in listener.incoming() {
            let mut sock = sock.unwrap();
            let mut buf = [0; 4096];
            sock.read(&mut buf).unwrap();
            sock.write_all(b"HTTP/1.1 200 OK\r\nContent-Length:0\r\n\r\n").unwrap();
        }
    });

    let client = Client::configure()
        .connector(DebugConnector(HttpConnector::new(1, &handle), Cell::new(0)))
        .no_proto()
        .build(&handle);

    let fut = stream::repeat(()).for_each(|()| {
        let url = format!("http://{}/a", addr).parse().unwrap();
        client.get(url)
            .and_then(|resp| {
                resp.body().collect()
            })
            .and_then(|_| {
                let timeout = Timeout::new(Duration::from_secs(1), &handle).unwrap();
                timeout.map_err(|e| e.into())
            })
            .or_else(|e| {
                println!("error {}", e);
                future::ok::<(), io::Error>(())
            })
    });

    core.run(fut).unwrap();
}

struct DebugConnector(HttpConnector, Cell<u32>);

impl Service for DebugConnector {
    type Request = Uri;
    type Response = DebugStream;
    type Error = io::Error;
    type Future = Box<Future<Item = DebugStream, Error = io::Error>>;

    fn call(&self, uri: Uri) -> Self::Future {
        let id = self.1.get();
        self.1.set(id + 1);
        println!("new connection {}", id);
        Box::new(self.0.call(uri).map(move |s| DebugStream(s, id)))
    }
}

struct DebugStream(TcpStream, u32);

impl Drop for DebugStream {
    fn drop(&mut self) {
        println!("socket {} dropping", self.1);
    }
}

impl Write for DebugStream {
    fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
        self.0.write(buf)
    }

    fn flush(&mut self) -> io::Result<()> {
        self.0.flush()
    }
}

impl AsyncWrite for DebugStream {
    fn shutdown(&mut self) -> futures::Poll<(), io::Error> {
        AsyncWrite::shutdown(&mut self.0)
    }
}

impl Read for DebugStream {
    fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        self.0.read(buf)
    }
}

impl AsyncRead for DebugStream {}
```

```
new connection 0
new connection 1
socket 0 dropping
thread 'main' panicked at 'dispatch dropped without returning error', /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.7/src/client/mod.rs:279:38
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:397
   4: std::panicking::begin_panic
             at src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:538
   6: <hyper::client::Client<C, B> as tokio_service::Service>::call::{{closure}}::{{closure}}
             at ./<panic macros>:3
   7: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll::{{closure}}
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/then.rs:33
   8: <futures::future::chain::Chain<A, B, C>>::poll
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/chain.rs:39
   9: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/then.rs:32
  10: <futures::future::chain::Chain<A, B, C>>::poll
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/chain.rs:32
  11: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/and_then.rs:32
  12: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/mod.rs:113
  13: <hyper::client::dns::IpAddrs as core::iter::iterator::Iterator>::next
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.7/src/client/mod.rs:151
  14: <futures::future::chain::Chain<A, B, C>>::poll
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/chain.rs:26
  15: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/and_then.rs:32
  16: <futures::future::chain::Chain<A, B, C>>::poll
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/chain.rs:26
  17: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/and_then.rs:32
  18: <futures::future::chain::Chain<A, B, C>>::poll
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/chain.rs:26
  19: <futures::future::or_else::OrElse<A, B, F> as futures::future::Future>::poll
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/or_else.rs:32
  20: <futures::stream::for_each::ForEach<S, F, U> as futures::future::Future>::poll
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/stream/for_each.rs:39
  21: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/mod.rs:288
  22: <futures::task_impl::Spawn<T>>::enter::{{closure}}
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/mod.rs:362
  23: futures::task_impl::std::set
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/std/mod.rs:78
  24: <futures::task_impl::Spawn<T>>::enter
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/mod.rs:362
  25: <futures::task_impl::Spawn<T>>::poll_future_notify
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/mod.rs:288
  26: tokio_core::reactor::Core::run::{{closure}}
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.10/src/reactor/mod.rs:235
  27: <scoped_tls::ScopedKey<T>>::set
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.0/src/lib.rs:135
  28: tokio_core::reactor::Core::run
             at /Users/sfackler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.10/src/reactor/mod.rs:234
  29: foo::main
             at src/main.rs:56
  30: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:99
  31: <std::rand::reader::ReaderRng<R> as rand::Rng>::fill_bytes
             at src/libstd/panicking.rs:459
             at src/libstd/panic.rs:361
             at src/libstd/rt.rs:59
  32: <foo::DebugStream as std::io::Read>::read
```

**Comment by seanmonstar** [comment]
Just tried running this with master, and nothing panics (and sockets are correctly dropped!)

**Comment by sfackler** [comment]
Ah cool - I was working against 0.11.7, but I'm also seeing the right behavior with master!
