### ISSUE TITLE
Problem with running example code from Server guide on Net BSD

### ISSUE THREAD

**Issue by MikHulk** [hyperium/hyper#1435]
Hi

I try to run this code https://hyper.rs/guides/server/hello-world/ on Net BSD 7.1 system, and I get an assertion error from mio at runtime.

The code woks on Debian 9.2. 

The error is apparently related to the EV_ERROR test ok kqueue.

Here the stacktrace:

```    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/http`
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `16384`', /home/mik/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.12/src/sys/unix/kqueue.rs:118:16
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: mio::sys::unix::kqueue::Selector::register
             at /home/mik/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.12/src/sys/unix/kqueue.rs:118
   8: <mio::sys::unix::eventedfd::EventedFd<'a> as mio::event_imp::Evented>::register
             at /home/mik/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.12/src/sys/unix/eventedfd.rs:96
   9: <mio::sys::unix::io::Io as mio::event_imp::Evented>::register
             at /home/mik/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.12/src/sys/unix/io.rs:65
  10: <mio::sys::unix::awakener::pipe::Awakener as mio::event_imp::Evented>::register
             at /home/mik/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.12/src/sys/unix/awakener.rs:63
  11: mio::poll::Poll::new
             at /home/mik/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.12/src/poll.rs:663
  12: tokio_core::reactor::Core::new
             at /home/mik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.12/src/reactor/mod.rs:150
  13: <hyper::server::Http<B>>::bind
             at /home/mik/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.11.16/src/server/mod.rs:187
  14: http::main
             at src/main.rs:25
  15: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  16: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  17: main
  18: _init
```

I am new with Rust and Hyper, could you help me with this error ? Is Hyper support NetBSD OS ?

Best,

**Comment by seanmonstar** [comment]
Looks like an assertion in the `mio` dependency is causing the panic. I can't recall if mio works on NetBSD. cc @carllerche

**Comment by carllerche** [comment]
Unfortunately, `netbsd` only compiles in CI as we don't have any resources to actually run the tests.

It is possible that there is a NetBSD only bug.

**Comment by MikHulk** [comment]
If you want I can test on Free BSD. I could try on VM with this OS.

**Comment by MikHulk** [comment]
I have tested on Free BSD 11.1, and hyper run on this OS. I will try to see with kqueue mainteners on NetBSD for help.

**Comment by seanmonstar** [comment]
I'm going to close this since there's nothing hyper can do here.
