### ISSUE TITLE
UnexpectedEof error on certain request

### ISSUE THREAD

**Issue by veeableful** [hyperium/hyper#1606]
Hi guys. I'm new to Rust and I'm also trying to write a Bing library for Rust as a way to learn the language. I'm using hyper v0.11.

I came across a problem when communicating with the [Custom Speech API](https://docs.microsoft.com/en-us/azure/cognitive-services/custom-speech-service/customspeech-how-to-topics/cognitive-services-custom-speech-use-endpoint) but not when I'm trying to communicate with the standard [Bing Speech API](https://docs.microsoft.com/en-us/azure/cognitive-services/speech/getstarted/getstartedrest). Here's the error that comes up when I try to use the Custom Speech API:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Hyper(Io(Custom { kind: Other, error: Custom { kind: Other, error: Kind(UnexpectedEof) } })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', libcore/result.rs:945:5
```
The only difference between the two APIs is the `Content-Type` header, the body and the Uri. However, they work fine when I use C++ version of the library which uses __libsoup__.

A dummy example that can reproduce the error is [here](https://gist.github.com/rust-play/f04550d6995230065d87c9efacc42607). The error occurs at line 122.

I don't see anything that could cause that error so I'm looking for some help :joy:

**Comment by seanmonstar** [comment]
Hm! Does it happen if you don't do the first request (wondering if it's a bug in a kept-alive connection)?

Would you be able to dump hyper's logs? Adding a crate like env_logger, and then re-running with `RUST_LOG=hyper` would show them (you may wish to scrub them for any secrets they show before pasting back).

**Comment by veeableful** [comment]
Hi @seanmonstar, It happens when I remove the first request. I've added `env_logger` and here's the output:
```
TRACE 2018-07-19T01:53:32Z: hyper::client::pool: park; waiting for idle connection: "https://westus.stt.speech.microsoft.com"
TRACE 2018-07-19T01:53:32Z: hyper::client::connect: Http::connect("https://westus.stt.speech.microsoft.com/speech/recognition/interactive/cognitiveservices/v1?language=en-US&cid=ENDPOINT_ID&format=detailed")
DEBUG 2018-07-19T01:53:32Z: hyper::client::dns: resolving host="westus.stt.speech.microsoft.com", port=443
DEBUG 2018-07-19T01:53:32Z: hyper::client::connect: connecting to 104.42.72.155:443
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: Other, error: Custom { kind: Other, error: Kind(UnexpectedEof) } })', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I've also run it with both requests where I set the subscription key and got the access token. Here's the output:
```
TRACE 2018-07-19T01:56:03Z: hyper::client::pool: park; waiting for idle connection: "https://westus.api.cognitive.microsoft.com"
TRACE 2018-07-19T01:56:03Z: hyper::client::connect: Http::connect("https://westus.api.cognitive.microsoft.com/sts/v1.0/issueToken")
DEBUG 2018-07-19T01:56:03Z: hyper::client::dns: resolving host="westus.api.cognitive.microsoft.com", port=443
DEBUG 2018-07-19T01:56:03Z: hyper::client::connect: connecting to 40.112.254.71:443
TRACE 2018-07-19T01:56:04Z: hyper::proto::h1::conn: read_keep_alive; is_mid_message=false
TRACE 2018-07-19T01:56:04Z: hyper::proto: should_keep_alive(version=Http11, header=None) = true
TRACE 2018-07-19T01:56:04Z: hyper::proto::h1::role: Client::encode has_body=true, method=None
TRACE 2018-07-19T01:56:04Z: hyper::proto::h1::io: reclaiming write buf Vec
TRACE 2018-07-19T01:56:04Z: hyper::proto::h1::io: detected no usage of vectored write, flattening
DEBUG 2018-07-19T01:56:04Z: hyper::proto::h1::io: flushed 169 bytes
TRACE 2018-07-19T01:56:04Z: hyper::proto::h1::io: reclaiming write buf Vec
DEBUG 2018-07-19T01:56:04Z: hyper::proto::h1::io: flushed 5 bytes
TRACE 2018-07-19T01:56:04Z: hyper::proto::h1::conn: flushed State { reading: Init, writing: KeepAlive, keep_alive: Busy, error: None }
TRACE 2018-07-19T01:56:04Z: hyper::proto::h1::conn: wants_read_again? false
TRACE 2018-07-19T01:56:05Z: hyper::proto::h1::conn: Conn::read_head
DEBUG 2018-07-19T01:56:05Z: hyper::proto::h1::io: read 1184 bytes
TRACE 2018-07-19T01:56:05Z: hyper::proto::h1::role: Response.parse([Header; 100], [u8; 1184])
TRACE 2018-07-19T01:56:05Z: hyper::proto::h1::role: Response.parse Complete(395)
TRACE 2018-07-19T01:56:05Z: hyper::header: maybe_literal not found, copying "Pragma"
TRACE 2018-07-19T01:56:05Z: hyper::header: maybe_literal not found, copying "X-AspNet-Version"
TRACE 2018-07-19T01:56:05Z: hyper::header: maybe_literal not found, copying "X-Powered-By"
TRACE 2018-07-19T01:56:05Z: hyper::header: maybe_literal not found, copying "apim-request-id"
TRACE 2018-07-19T01:56:05Z: hyper::header: maybe_literal not found, copying "x-content-type-options"
DEBUG 2018-07-19T01:56:05Z: hyper::proto::h1::io: parsed 11 headers (395 bytes)
DEBUG 2018-07-19T01:56:05Z: hyper::proto::h1::conn: incoming body is content-length (789 bytes)
TRACE 2018-07-19T01:56:05Z: hyper::proto: expecting_continue(version=Http11, header=None) = false
TRACE 2018-07-19T01:56:05Z: hyper::proto: should_keep_alive(version=Http11, header=None) = true
TRACE 2018-07-19T01:56:05Z: hyper::proto::h1::conn: Conn::read_body
TRACE 2018-07-19T01:56:05Z: hyper::proto::h1::decode: decode; state=Length(789)
TRACE 2018-07-19T01:56:05Z: hyper::proto::h1::conn: flushed State { reading: Body(Length(0)), writing: KeepAlive, keep_alive: Busy, error: None }
TRACE 2018-07-19T01:56:05Z: hyper::proto::h1::conn: wants_read_again? false
TRACE 2018-07-19T01:56:05Z: hyper::proto::h1::conn: Conn::read_body
TRACE 2018-07-19T01:56:05Z: hyper::proto::h1::decode: decode; state=Length(0)
DEBUG 2018-07-19T01:56:05Z: hyper::proto::h1::conn: incoming body completed
TRACE 2018-07-19T01:56:05Z: hyper::proto::h1::conn: maybe_notify; read_from_io blocked
TRACE 2018-07-19T01:56:05Z: hyper::proto::h1::conn: read_keep_alive; is_mid_message=false
TRACE 2018-07-19T01:56:05Z: hyper::proto::h1::conn: flushed State { reading: Init, writing: Init, keep_alive: Idle, error: None }
TRACE 2018-07-19T01:56:05Z: hyper::proto::h1::conn: wants_read_again? false
TRACE 2018-07-19T01:56:05Z: hyper::client::pool: Pool::put "https://westus.api.cognitive.microsoft.com"
DEBUG 2018-07-19T01:56:05Z: hyper::client::pool: pooling idle connection for "https://westus.api.cognitive.microsoft.com"
Got token: eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1cm46bXMuY29nbml0aXZlc2VydmljZXMiLCJleHAiOiIxNTMxOTY1OTY1IiwicmVnaW9uIjoid2VzdHVzIiwic3Vic2NyaXB0aW9uLWlkIjoiOGE5ODE4NDU5ODNhNGM5M2JlMWU0MjNhMWNkY2E5N2QiLCJwcm9kdWN0LWlkIjoiQ1JJUy5TMiIsImNvZ25pdGl2ZS1zZXJ2aWNlcy1lbmRwb2ludCI6Imh0dHBzOi8vYXBpLmNvZ25pdGl2ZS5taWNyb3NvZnQuY29tL2ludGVybmFsL3YxLjAvIiwiYXp1cmUtcmVzb3VyY2UtaWQiOiIvc3Vic2NyaXB0aW9ucy9iZDAxMDU0YS01MzFiLTQ1OWMtOGY2Zi0zODg3ZDRlOGFmOWQvcmVzb3VyY2VHcm91cHMvQ3VzdG9tU3BlZWNoL3Byb3ZpZGVycy9NaWNyb3NvZnQuQ29nbml0aXZlU2VydmljZXMvYWNjb3VudHMvQ3VzdG9tU3BlZWNoIiwic2NvcGUiOiJodHRwczovL3dlc3R1cy5hcGkuY29nbml0aXZlLm1pY3Jvc29mdC5jb20vY3VzdG9tc3BlZWNoIiwiYXVkIjoidXJuOm1zLmN1c3RvbXNwZWVjaCJ9.21TNU0nIbm5uJjhTaRU3WRADZXNdbUU9UcgMDgzRISg
TRACE 2018-07-19T01:56:05Z: hyper::client::pool: park; waiting for idle connection: "https://westus.stt.speech.microsoft.com"
TRACE 2018-07-19T01:56:05Z: hyper::client::connect: Http::connect("https://westus.stt.speech.microsoft.com/speech/recognition/interactive/cognitiveservices/v1?language=en-US&cid=this-is-some-endpoint-id&format=detailed")
DEBUG 2018-07-19T01:56:05Z: hyper::client::dns: resolving host="westus.stt.speech.microsoft.com", port=443
DEBUG 2018-07-19T01:56:05Z: hyper::client::connect: connecting to 104.42.72.155:443
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: Other, error: Custom { kind: Other, error: Kind(UnexpectedEof) } })', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by seanmonstar** [comment]
Aha! The logs suggest that it gets as far as trying to establish a connection, and then errors. So, it's failing at either the TCP or the TLS handshake. It seems likely its the TLS handshake, since the error for TCP would have been more descriptive.

**Comment by veeableful** [comment]
I tried updating the dependencies to the latest versions hoping there's a fix but there doesn't seem a fix for it yet. Where should I be reporting this issue if it really is the TLS handshake problem? :sweat_smile:

**Comment by seanmonstar** [comment]
If it is a bug in the TLS library, that'd be where to file about that. However, it might not necessarily be a bug, and instead just require you configure the TLS connector specifically for whatever the Custom Speech API might need.

**Comment by seanmonstar** [comment]
I'm going to close as it doesn't seem like a bug in hyper, but if you have more questions, ask :)
