### ISSUE TITLE
entered unreachable code

### ISSUE THREAD

**Issue by x1957** [hyperium/hyper#1996]
```
thread 'tokio-runtime-worker-66' panicked at 'internal error: entered unreachable code', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.0-alpha.1/src/client/pool.rs:657:42
stack backtrace:
0: backtrace::backtrace::libunwind::trace
at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
1: backtrace::backtrace::trace_unsynchronized
at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
2: std::sys_common::backtrace::_print_fmt
at src/libstd/sys_common/backtrace.rs:76
3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
at src/libstd/sys_common/backtrace.rs:60
4: core::fmt::write
at src/libcore/fmt/mod.rs:1028
5: std::io::Write::write_fmt
at src/libstd/io/mod.rs:1412
6: std::sys_common::backtrace::_print
at src/libstd/sys_common/backtrace.rs:64
7: std::sys_common::backtrace::print
at src/libstd/sys_common/backtrace.rs:49
8: std::panicking::default_hook::{{closure}}
at src/libstd/panicking.rs:196
9: std::panicking::default_hook
at src/libstd/panicking.rs:210
10: std::panicking::rust_panic_with_hook
at src/libstd/panicking.rs:473
11: std::panicking::begin_panic
12: <hyper::client::pool::Checkout<T> as core::future::future::Future>::poll
13: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
14: futures_util::future::chain::Chain<Fut1,Fut2,Data>::poll
15: futures_util::try_future::try_chain::TryChain<Fut1,Fut2,Data>::poll
16: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
17: <hyper::client::ResponseFuture as core::future::future::Future>::poll
18: <reqwest::async_impl::client::PendingRequest as core::future::future::Future>::poll
19: <reqwest::async_impl::client::Pending as core::future::future::Future>::poll
20: std::future::poll_with_tls_context
21: <std::future::GenFuture<T> as core::future::future::Future>::poll
22: <std::future::GenFuture<T> as core::future::future::Future>::poll
23: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
24: std::panicking::try::do_call
25: __rust_maybe_catch_panic
at src/libpanic_unwind/lib.rs:80
26: tokio_executor::threadpool::task::Task::run
27: tokio_executor::threadpool::worker::Worker::run_task
28: tokio_executor::threadpool::worker::Worker::run
29: tracing_core::dispatcher::with_default
30: std::thread::local::LocalKey<T>::with
31: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
32: std::thread::local::LocalKey<T>::with
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace
```

**Comment by swarmer** [comment]
I believe I encountered the same error:

```
thread 'tokio-runtime-worker-0' panicked at 'internal error: entered unreachable code', /home/swarmer/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.0-alpha.4/src/client/pool.rs:659:42
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::begin_panic
             at /rustc/224f0bc90c010b88ca6ec600c9b02f6e3638d78e/src/libstd/panicking.rs:407
  12: <hyper::client::pool::Checkout<T> as core::future::future::Future>::poll::{{closure}}
             at ./<::std::macros::panic macros>:3
```
