### ISSUE TITLE
`'Out of bounds access'` and `'dispatch dropped without returning error'` panicks on mocked test (code included)

### ISSUE THREAD

**Issue by ErichDonGubler** [hyperium/hyper#2107]
I've been trying to maintain [`yup-hyper-mock`](https://github.com/Byron/yup-hyper-mock) as part of efforts to get [`yup-oauth2`](https://github.com/dermesser/yup-oauth2) and later [`google-apis-rs`](https://github.com/Byron/google-apis-rs) updated to use `async`/`await`. It's gone mostly smoothly until I started having issues with one of the last test cases whose details I've tried to minimize in  [this repo](https://gitlab.com/erichdongubler-mre/2020-01-hyper-problems) -- is there a contract I'm violating here, or is this a legitimate bug? I'm not sure. I've inlined the relevant code and output below for your convenience:

<details>
<summary>
<code>main.rs</code>
</summary>

```rust
use {
    futures::future::{self, ok},
    hyper::{
        client::{
            connect::{Connected, Connection},
            Client,
        },
        service::Service,
        Body, Uri,
    },
    log::LevelFilter,
    std::{
        cmp::min,
        io,
        pin::Pin,
        task::{Context, Poll, Waker},
    },
    tokio::io::{AsyncRead, AsyncWrite},
};

pub struct MockPollStream {
    data: Vec<u8>,
    pos: usize,
    ready_for_response: bool,
    waker: Option<Waker>,
}

impl MockPollStream {
    pub fn new(data: Vec<u8>) -> Self {
        Self {
            data,
            pos: 0,
            ready_for_response: false,
            waker: None,
        }
    }
}

impl AsyncRead for MockPollStream {
    fn poll_read(
        mut self: Pin<&mut Self>,
        cx: &mut Context,
        buf: &mut [u8],
    ) -> Poll<io::Result<usize>> {
        self.waker = Some(cx.waker().clone());
        if !self.ready_for_response {
            return Poll::Pending;
        }
        let n = min(buf.len(), self.data.len() - self.pos);
        let read_until = self.pos + n;
        buf[..n].copy_from_slice(&self.data[self.pos..read_until]);
        self.pos = read_until;
        Poll::Ready(Ok(n))
    }
}

impl AsyncWrite for MockPollStream {
    fn poll_write(
        self: Pin<&mut Self>,
        _cx: &mut Context,
        _data: &[u8],
    ) -> Poll<io::Result<usize>> {
        let Self {
            data,
            ready_for_response,
            waker,
            ..
        } = self.get_mut();
        *ready_for_response = true;
        if let Some(w) = waker.take() {
            w.wake();
        }
        Poll::Ready(Ok(data.len()))
    }

    fn poll_flush(self: Pin<&mut Self>, _cx: &mut Context) -> Poll<io::Result<()>> {
        Poll::Ready(Ok(()))
    }

    fn poll_shutdown(self: Pin<&mut Self>, _cx: &mut Context) -> Poll<io::Result<()>> {
        Poll::Ready(Ok(()))
    }
}

impl Connection for MockPollStream {
    fn connected(&self) -> Connected {
        Connected::new()
    }
}

#[derive(Default, Clone)]
pub struct DummyConnector;

impl Service<Uri> for DummyConnector {
    type Response = MockPollStream;
    type Error = std::io::Error;
    type Future = future::Ready<Result<Self::Response, Self::Error>>;

    fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        Poll::Ready(Ok(()))
    }

    fn call(&mut self, _req: Uri) -> Self::Future {
        ok(MockPollStream::new("asdf".to_owned().into_bytes()))
    }
}

#[tokio::main]
async fn main() {
    env_logger::builder()
        .filter_level(LevelFilter::Trace)
        .init();
    let client = Client::builder().build::<_, Body>(DummyConnector::default());
    let _ = client
        .get("http://127.0.0.1".parse().unwrap())
        .await
        .unwrap();
}
```

</details>

Output on my machine:

```
~/Downloads/hyper_problems master$ cargo run
   Compiling 2020-01-hyper-problems v0.1.0 (/home/erichdongubler/Downloads/hyper_problems)
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/2020-01-hyper-problems`
[2020-01-10T18:56:21Z TRACE hyper::client::pool] checkout waiting for idle connection: "http://127.0.0.1"
[2020-01-10T18:56:21Z TRACE hyper::client::conn] client handshake HTTP/1
[2020-01-10T18:56:21Z TRACE hyper::client] handshake complete, spawning background dispatcher task
[2020-01-10T18:56:21Z TRACE want] signal: Want
[2020-01-10T18:56:21Z TRACE want] signal found waiting giver, notifying
[2020-01-10T18:56:21Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Busy }
[2020-01-10T18:56:21Z TRACE want] poll_want: taker wants!
[2020-01-10T18:56:21Z TRACE hyper::client::pool] checkout dropped for "http://127.0.0.1"
[2020-01-10T18:56:21Z TRACE hyper::proto::h1::role] Client::encode method=GET, body=None
[2020-01-10T18:56:21Z TRACE hyper::proto::h1::io] detected no usage of vectored write, flattening
[2020-01-10T18:56:21Z DEBUG hyper::proto::h1::io] flushed 4 bytes
[2020-01-10T18:56:21Z DEBUG hyper::proto::h1::io] flushed 4 bytes
[2020-01-10T18:56:21Z DEBUG hyper::proto::h1::io] flushed 4 bytes
[2020-01-10T18:56:21Z DEBUG hyper::proto::h1::io] flushed 4 bytes
[2020-01-10T18:56:21Z DEBUG hyper::proto::h1::io] flushed 4 bytes
[2020-01-10T18:56:21Z DEBUG hyper::proto::h1::io] flushed 4 bytes
[2020-01-10T18:56:21Z DEBUG hyper::proto::h1::io] flushed 4 bytes
[2020-01-10T18:56:21Z DEBUG hyper::proto::h1::io] flushed 4 bytes
thread 'main' panicked at 'Out of bounds access', src/libcore/option.rs:1185:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::option::expect_failed
             at src/libcore/option.rs:1185
  15: core::option::Option<T>::expect
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/option.rs:345
  16: <alloc::collections::vec_deque::VecDeque<A> as core::ops::index::IndexMut<usize>>::index_mut
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/collections/vec_deque.rs:2738
  17: <hyper::common::buf::BufList<T> as bytes::buf::buf_impl::Buf>::advance
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.1/src/common/buf.rs:47
  18: <hyper::proto::h1::io::WriteBuf<B> as bytes::buf::buf_impl::Buf>::advance
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.1/src/proto/h1/io.rs:537
  19: <hyper::proto::h1::io::WriteBufAuto<B> as bytes::buf::buf_impl::Buf>::advance
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.1/src/proto/h1/io.rs:580
  20: tokio::io::async_write::AsyncWrite::poll_write_buf
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/io/async_write.rs:149
  21: hyper::proto::h1::io::Buffered<T,B>::poll_flush
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.1/src/proto/h1/io.rs:225
  22: hyper::proto::h1::conn::Conn<I,B,T>::poll_flush
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.1/src/proto/h1/conn.rs:628
  23: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_flush
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.1/src/proto/h1/dispatch.rs:363
  24: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.1/src/proto/h1/dispatch.rs:151
  25: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.1/src/proto/h1/dispatch.rs:126
  26: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.1/src/proto/h1/dispatch.rs:109
  27: <hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T> as core::future::future::Future>::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.1/src/proto/h1/dispatch.rs:409
  28: <hyper::client::conn::ProtoClient<T,B> as core::future::future::Future>::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.1/src/client/conn.rs:601
  29: <hyper::client::conn::Connection<T,B> as core::future::future::Future>::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.1/src/client/conn.rs:391
  30: <F as futures_core::future::TryFuture>::try_poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.1/src/future.rs:83
  31: <futures_util::future::try_future::map_err::MapErr<Fut,F> as core::future::future::Future>::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.1/src/future/try_future/map_err.rs:43
  32: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.1/src/future/future/map.rs:40
  33: tokio::task::core::Core<T>::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/core.rs:128
  34: tokio::task::harness::Harness<T,S>::poll::{{closure}}::{{closure}}
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/harness.rs:120
  35: core::ops::function::FnOnce::call_once
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/ops/function.rs:227
  36: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panic.rs:317
  37: std::panicking::try::do_call
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:287
  38: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  39: std::panicking::try
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:265
  40: std::panic::catch_unwind
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panic.rs:396
  41: tokio::task::harness::Harness<T,S>::poll::{{closure}}
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/harness.rs:101
  42: tokio::loom::std::causal_cell::CausalCell<T>::with_mut
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/loom/std/causal_cell.rs:41
  43: tokio::task::harness::Harness<T,S>::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/harness.rs:100
  44: tokio::task::raw::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/raw.rs:162
  45: tokio::task::raw::RawTask::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/raw.rs:113
  46: tokio::task::Task<S>::run
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/mod.rs:371
  47: tokio::runtime::basic_scheduler::SchedulerPriv::tick
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/basic_scheduler.rs:192
  48: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/basic_scheduler.rs:142
  49: tokio::runtime::Runtime::block_on::{{closure}}
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/mod.rs:411
  50: tokio::runtime::context::enter
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/context.rs:72
  51: tokio::runtime::handle::Handle::enter
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/handle.rs:33
  52: tokio::runtime::Runtime::block_on
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/mod.rs:408
  53: _2020_01_hyper_problems::main
             at src/main.rs:108
  54: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  55: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  56: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  57: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  58: std::panicking::try
             at src/libstd/panicking.rs:265
  59: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  60: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  61: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  62: main
  63: __libc_start_main
  64: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2020-01-10T18:56:21Z TRACE want] signal: Closed
thread 'main' panicked at 'dispatch dropped without returning error', /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.1/src/client/conn.rs:236:35
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::begin_panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:400
  12: hyper::client::conn::SendRequest<B>::send_request_retryable::{{closure}}
             at ./<::std::macros::panic macros>:3
  13: <futures_util::future::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll::{{closure}}
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.1/src/future/future/then.rs:44
  14: futures_util::future::future::chain::Chain<Fut1,Fut2,Data>::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.1/src/future/future/chain.rs:54
  15: <futures_util::future::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.1/src/future/future/then.rs:44
  16: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.1/src/future/either.rs:62
  17: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.1/src/future/either.rs:62
  18: <F as futures_core::future::TryFuture>::try_poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.1/src/future.rs:83
  19: <futures_util::future::try_future::map_err::MapErr<Fut,F> as core::future::future::Future>::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.1/src/future/try_future/map_err.rs:43
  20: <F as futures_core::future::TryFuture>::try_poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.1/src/future.rs:83
  21: <futures_util::future::try_future::map_ok::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.1/src/future/try_future/map_ok.rs:45
  22: <F as futures_core::future::TryFuture>::try_poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.1/src/future.rs:83
  23: <futures_util::future::try_future::map_ok::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.1/src/future/try_future/map_ok.rs:45
  24: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.1/src/future/either.rs:63
  25: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.1/src/future/either.rs:63
  26: <F as futures_core::future::TryFuture>::try_poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.1/src/future.rs:83
  27: futures_util::future::try_future::try_chain::TryChain<Fut1,Fut2,Data>::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.1/src/future/try_future/try_chain.rs:58
  28: <futures_util::future::try_future::and_then::AndThen<Fut1,Fut2,F> as core::future::future::Future>::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.1/src/future/try_future/and_then.rs:46
  29: hyper::client::Client<C,B>::retryably_send_request::{{closure}}
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.1/src/client/mod.rs:254
  30: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.1/src/future/poll_fn.rs:54
  31: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/future/future.rs:119
  32: <hyper::client::ResponseFuture as core::future::future::Future>::poll
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.1/src/client/mod.rs:607
  33: std::future::poll_with_tls_context::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:121
  34: std::future::get_task_context
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:111
  35: std::future::poll_with_tls_context
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:121
  36: _2020_01_hyper_problems::main::{{closure}}
             at src/main.rs:114
  37: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:43
  38: std::future::set_task_context
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:79
  39: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:43
  40: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/basic_scheduler.rs:138
  41: tokio::runtime::Runtime::block_on::{{closure}}
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/mod.rs:411
  42: tokio::runtime::context::enter
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/context.rs:72
  43: tokio::runtime::handle::Handle::enter
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/handle.rs:33
  44: tokio::runtime::Runtime::block_on
             at /home/erichdongubler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/mod.rs:408
  45: _2020_01_hyper_problems::main
             at src/main.rs:108
  46: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  47: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  48: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  49: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  50: std::panicking::try
             at src/libstd/panicking.rs:265
  51: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  52: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  53: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  54: main
  55: __libc_start_main
  56: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

I don't think it's relevant here, but in case it helps, I've been developing on a `x86_64-unknown-linux-gnu` with a Fedora installation. I can provide more environmental details if you need them too. :)

**Comment by seanmonstar** [comment]
Could you enable `RUST_BACKTRACE=1` and paste the results?

**Comment by ErichDonGubler** [comment]
@seanmonstar: Wow! That was fast. I've updated the OP. :)

**Comment by seanmonstar** [comment]
Ah ok, I see. The problem is your `AsyncWrite` is returning that it wrote more data than hyper provided. It would be good for hyper to detect this with a better message, but it'd still be a contract violation.

**Comment by ErichDonGubler** [comment]
AAAHHH, I figured it out with that hint! :) I am shadowing `data` with `MockPollStream::data` and throwing away the `data` provided to `<MockPollStream as AsyncWrite>::poll_write`. Ugh. Thank you so much for the help!
