### ISSUE TITLE
panicked at 'header name validated by httparse: InvalidHeaderName', ... src/proto/h1/role.rs:659:28

### ISSUE THREAD

**Issue by kosta** [hyperium/hyper#2280]
My son is writing a web crawler in rust and hyper panicked at:

```
thread 'tokio-runtime-worker' panicked at 'header name validated by httparse: InvalidHeaderName', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.7/src/proto/h1/role.rs:659:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'dispatch dropped without returning error', /build/rust/src/rustc-1.46.0-src/src/libstd/macros.rs:13:23
```

I can try to find the url that caused this to have more information about what caused this issue exactly.

The panic is caused by the `header_name` macro which basically calls:

```
HeaderName::from_bytes($bytes).expect("header name validated by httparse")
```

Would it make more sense to return a parse error here instad of expect? On the other hand, the header_value is using unsafe and assumes httparse and hyper agree on how to parse headers. It could be important to try to figure out and fix the underlying issue.

**Comment by seanmonstar** [comment]
That panic means an internal bug. Do you happen to have the text that was meant to be parsed?

**Comment by kosta** [comment]
I might be able to reproduce the url. If so, I will access it with a debug build to get the header.

**Comment by kosta** [comment]
I have no time to reproduce this weekend, but here is the list of URLs that were being processed by the program when it paniced. If this is a persistent issue, it should panic again. (Sorry, this is a CSV export from the db, hence the CSV quoting...). If I hear nothing back, I'll try to reproduce next week.

```
"https://en.wikipedia.org/wiki/US_labor_law#cite_ref-22"
"https://en.wikipedia.org/wiki/United_States_Congress#cite_ref-97"
"https://en.wikipedia.org/wiki/United_States_Constitution#cite_ref-42"
"https://en.wikipedia.org/wiki/United_States_Constitution#cite_ref-41"
"https://en.wikipedia.org/wiki/United_States_Constitution#cite_ref-47"
"https://en.wikipedia.org/wiki/United_States_Congress#cite_ref-DCMacnutsSuperCoolTool01_156-0"
"https://en.wikipedia.org/wiki/US_labor_law#cite_ref-226"
"https://en.wikipedia.org/wiki/United_States_Constitution#cite_ref-46"
"https://en.wikipedia.org/wiki/US_labor_law#cite_ref-224"
"https://en.wikipedia.org/wiki/United_States_Congress#cite_ref-Coner_39-0"
"https://en.wikipedia.org/wiki/United_States_Congress#cite_ref-Census_181-0"
"http://dblp.uni-trier.de/pers/hd/g/Garcia=Molina:Hector"
"https://github.com/tootsuite/mastodon/network/members"
"http://cs.illinois.edu/academics/graduate/phd-program/guidelines-forming-phd-committee"
"https://github.com/tootsuite/mastodon/pull/13582"
"http://www.christianholz.net/"
"https://karmanhealthcare.com/#uaw"
"https://shc.uci.edu/about#main-content"
"http://www.ruby-doc.org/core/Enumerable.html#method-i-find_all"
"https://www.unaids.org/en/regionscountries/countries/mauritania"
"https://shc.uci.edu/about/about-shc/accreditation"
"https://github.com/contributte/neonizer"
"http://www.ruby-doc.org/core/Enumerable.html#method-i-find_index"
"https://labfinder.com/#uaw"
"https://learning.oreilly.com/library/view/security-and-usability/0596008279/ch13.html#securityusability-CHP-13-SECT-2.1.4"
"http://cs.illinois.edu/academics/graduate/phd-program/phd-time-limits-milestones"
"https://snouts.online/@Ophillous"
"https://github.com/tootsuite/mastodon/pull/13946"
"http://nosh.northwestern.edu/media/whitehouse.pdf"
"https://familydoctor.org/your-health-resources/healthcare-management/doctors-notes/"
"https://www.toyotadirect.com/#uaw"
"https://news.cornell.edu/sites/default/files/styles/full_size/public/2020-08/0819_tcat2.jpg?"
"https://dc.library.okstate.edu/digital/collection/kapplers/id/26383/"
"http://lgbtq.uchicago.edu""/"
"https://www.lti.cs.cmu.edu/people/16912/yubin-kim"
"https://www.engr.wisc.edu/department/electrical-computer-engineering/"
"https://www.gnu.org/software/fm/"
"https://en.wikipedia.org/wiki/United_States_Congress#cite_ref-68"
"https://en.wikipedia.org/wiki/United_States_Congress#cite_ref-64"
"https://en.wikipedia.org/wiki/US_labor_law#cite_ref-217"
"https://en.wikipedia.org/wiki/US_labor_law#cite_ref-219"
"https://en.wikipedia.org/wiki/United_States_Constitution#cite_ref-40"
"https://en.wikipedia.org/wiki/US_labor_law#cite_ref-216"
"https://en.wikipedia.org/wiki/United_States_Constitution#cite_ref-44"
"https://en.wikipedia.org/wiki/US_labor_law#cite_ref-222"
"https://en.wikipedia.org/wiki/United_States_Congress#cite_ref-CRS_Report_about_CRS_120-0"
"https://en.wikipedia.org/wiki/United_States_Congress#cite_ref-75"
"https://en.wikipedia.org/wiki/United_States_Congress#cite_ref-9"
"https://en.wikipedia.org/wiki/United_States_Congress#cite_ref-98"
"https://en.wikipedia.org/wiki/US_labor_law#cite_ref-220"
"https://en.wikipedia.org/wiki/US_labor_law#cite_ref-221"
"https://en.wikipedia.org/wiki/United_States_Constitution#cite_ref-43"
"https://en.wikipedia.org/wiki/Plame_affair#cite_note-13"
"https://en.wikipedia.org/wiki/United_States_Congress#cite_ref-DCMacnutsSuperCoolTool03_145-0"
"https://en.wikipedia.org/wiki/US_labor_law#cite_ref-227"
"https://en.wikipedia.org/wiki/United_States_Constitution#cite_ref-49"
"https://en.wikipedia.org/wiki/United_States_Constitution#cite_ref-50"
"https://en.wikipedia.org/wiki/US_labor_law#cite_ref-228"
"https://en.wikipedia.org/wiki/United_States_Congress#cite_ref-DCMacnutsSuperCoolTool02_73-0"
"https://en.wikipedia.org/wiki/Plame_affair#cite_note-127"
"https://en.wikipedia.org/wiki/US_labor_law#cite_ref-223"
"https://en.wikipedia.org/wiki/Polarization_(politics)#cite_ref-78"
"https://en.wikipedia.org/wiki/Plame_affair#cite_note-128"
"https://en.wikipedia.org/wiki/Polarization_(politics)#cite_ref-76"
"https://en.wikipedia.org/wiki/Polarization_(politics)#cite_ref-66"
"https://en.wikipedia.org/wiki/United_States_Constitution#cite_ref-45"
"https://en.wikipedia.org/wiki/Plame_affair#cite_note-126"
"https://en.wikipedia.org/wiki/Legislation_of_the_United_Kingdom"
"https://en.wikipedia.org/wiki/Plame_affair#cite_note-129"
"https://en.wikipedia.org/wiki/List_of_Acts_of_the_Northern_Ireland_Assembly"
"https://en.wikipedia.org/wiki/Socialist_state"
"https://en.wikipedia.org/wiki/US_labor_law#cite_ref-229"
"https://en.wikipedia.org/wiki/Plame_affair#cite_note-131"
"https://en.wikipedia.org/wiki/United_States_Congress#cite_ref-Dem9834_34-0"
"https://en.wikipedia.org/wiki/United_States_Constitution#cite_ref-55"
"https://www.gcu.edu/degree-programs/bachelor-science-sociology-social-work"
"https://en.wikipedia.org/wiki/US_labor_law#cite_ref-231"
"https://en.wikipedia.org/wiki/Polarization_(politics)#cite_ref-86"
"https://en.wikipedia.org/wiki/Plame_affair#cite_note-133"
"https://en.wikipedia.org/wiki/Socialist_democracy"
"https://en.wikipedia.org/wiki/Sovereignty_Council_of_Sudan"
"https://en.wikipedia.org/wiki/United_States_Congress#cite_ref-DCMacnutsSuperCoolTool05_153-0"
"https://en.wikipedia.org/wiki/US_labor_law#cite_ref-233"
"https://en.wikipedia.org/wiki/US_labor_law#cite_ref-232"
"https://www.gcu.edu/degree-programs/bs-applied-marketing-advertising"
"http://depts.washington.edu/anesth/research/centers/index.shtml"
"http://depts.washington.edu/anesth/education/residents/residentlist.shtml"
"https://en.wikipedia.org/wiki/United_States_Constitution#cite_ref-56"
"https://en.wikipedia.org/wiki/United_States_Constitution#cite_ref-57"
"https://en.wikipedia.org/wiki/Polarization_(politics)#cite_ref-85"
"https://www.gcu.edu/degree-programs/bachelor-science-sociology"
"https://en.wikipedia.org/wiki/United_States_Congress#cite_ref-English14_33-0"
"https://en.wikipedia.org/wiki/United_States_Constitution#cite_ref-58"
"https://en.wikipedia.org/wiki/South_West_Caucasian_Republic"
"https://dblp.org/rec/conf/vw/ChengSFCZ00.html?#references"
"https://en.wikipedia.org/wiki/Plame_affair#cite_note-130"
"https://www.gcu.edu/degree-programs/bachelor-science-sports-management"
"https://en.wikipedia.org/wiki/Polarization_(politics)#cite_ref-84"
"https://en.wikipedia.org/wiki/Plame_affair#cite_note-132"
"https://en.wikipedia.org/wiki/Plame_affair#cite_note-134"
"http://dance.washington.edu/programs-courses"
"https://en.wikipedia.org/wiki/US_labor_law#cite_ref-23"
"http://depts.washington.edu/anesth/research/centers/hiprc/index.shtml"
"https://en.wikipedia.org/wiki/Ware_v._Hylton#mw-head"
"https://en.wikipedia.org/wiki/United_States_Constitution#cite_ref-54"
"http://dance.washington.edu/recent-changes-increase-diversity-and-equity"
"http://depts.washington.edu/anesth/feedback.shtml"
"https://en.wikipedia.org/wiki/United_States_Congress#cite_ref-DCMacnutsSuperCoolTool04_139-0"
"https://en.wikipedia.org/wiki/Polarization_(politics)#cite_ref-79"
"https://en.wikipedia.org/wiki/Polarization_(politics)#cite_ref-83"
"https://en.wikipedia.org/wiki/United_States_Congress#cite_ref-English14_33-1"
"http://depts.washington.edu/anesth/research/academicevening/index.shtml"
"http://dblp.uni-trier.de/pers/hd/b/Balakrishnan:Hari"
"http://dblp.uni-trier.de/pers/hd/p/Prade:Henri"
"http://dblp.uni-trier.de/pers/hd/z/Zhang:HongJiang"
"http://dblp.uni-trier.de/pers/hd/s/Simon:Herbert_A="
"http://hpi.de/en/imprint.html"
"https://www.engr.wisc.edu/department/biomedical-engineering/"
"http://hpi.de/en/sitemap.html"
"http://kaji-lab.jp/en/index.php?"
"http://www.ruby-doc.org/core/Enumerable.html#method-i-find"
"http://cs.illinois.edu/academics/graduate/phd-program/phd-ms-thesis-format-review-guidelines"
"https://www.engr.wisc.edu/department/cbe/"
"http://cs.illinois.edu/academics/graduate/phd-program/phd-program-study-process"
"https://github.com/contributte"
"https://slime.global/@Aleums/104706123036453365"
"http://www.who.int/redirect-pages/mega-menu/countries/regions/south-east-asia"
"https://blogs.mtu.edu/diversity-center/"
"https://blogs.mtu.edu/archives/2020/07/27/#main"
"https://www.engr.wisc.edu/department/civil-environmental-engineering/"
"http://www.ruby-doc.org/core/Enumerable.html#method-i-first"
"https://recruit-holdings.com/newsroom/#holdings-pressrelease"
"http://cs.illinois.edu/academics/graduate/phd-program/phd-requirements"
"https://github.com/tootsuite/mastodon/pull/13773"
"https://www.lti.cs.cmu.edu/people/16914/lu-jiang"
"https://staycobblestone.com/#uaw"
"https://legacycommunityhealth.org/#uaw"
"https://www.gnu.org/software/gnue/"
"https://github.com/jonhue/turbolinks-animate/issues"
"https://news.cornell.edu/stories/2020/08/study-machine-learning-can-predict-market-behavior#main"
"http://ludwig-wall.de/"
"https://acrobat.adobe.com/us/en/business/integrations/google-drive.html"
"https://blogs.mtu.edu/archives/2020/07/27/#mtu-footer"
"https://recruit-holdings.com/newsroom/#openSearch"
"https://shc.uci.edu/about/about-shc/general-information"
"https://canvas.uw.edu/courses/721562/external_tools/46189"
"http://www.who.int/redirect-pages/mega-menu/countries/regions/western-pacific"
"http://www.hbenko.com/"
"https://www.unaids.org/en/regionscountries/countries/mexico"
"http://www.google.com/edu/#get-updates"
"https://dl.acm.org/sigs"
"https://mastodon.social/interact/104713673140521763?"
"https://mastodon.social/interact/103397492584370087?"
"https://www.engr.wisc.edu/department/engineering-physics/"
"https://snouts.online/@Ophillous/104714288847001658"
```

**Comment by kosta** [comment]
Unfortunately, I was not able to reproduce the issue with any of the provided urls (however I found a bug in https://github.com/seanmonstar/reqwest/pull/1034). Maybe it was a flipped bit or a bad server or similar that got fixed/restarted/....?

I would propose to at least change the `expect()` in `header_name!` to always include the offending bytes, so that if the issue resurfaces, we at least know the values that caused this.
