### ISSUE TITLE
Polling a connection after upgrade results in a panic

### ISSUE THREAD

**Issue by lucacasonato** [hyperium/hyper#2588]
**Version**

Hyper 0.14.9. Also present on commit c3f3330bddb2b411ef119cff03c0a5d11bb7bdd4

**Platform**

x64 Linux, kernel 5.4.0-77-generic

**Description**

Calling `UpgradeableConnection::poll` after upgrading a HTTP/1.1 connection by calling `hyper::upgrade::on` on a request originating from that connection results in a panic. I would instead expect that the poll following the upgrade doesn't panic, but returns `Poll::Ready` (because hyper is now not involved in this connection anymore).

<details>
<summary>Stack Backtrace</summary>

Only frame 3 and 4 are interesting here.

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/lucacasonato/.cargo/git/checkouts/hyper-244adc33bc9861b8/c3f3330/src/server/conn.rs:1226:64
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:386:21
   4: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
             at /home/lucacasonato/.cargo/git/checkouts/hyper-244adc33bc9861b8/c3f3330/src/server/conn.rs:1226:39
   5: futures_util::future::future::FutureExt::poll_unpin
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/future/mod.rs:562:9
   6: deno_runtime::ops::http::ConnResource::poll
             at ./runtime/ops/http.rs:121:27
   7: deno_runtime::ops::http::op_http_request_next::{{closure}}::{{closure}}
             at ./runtime/ops/http.rs:169:35
   8: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/poll_fn.rs:56:9
   9: deno_core::async_cancel::internal::<impl deno_core::async_cancel::Cancelable<F>>::poll_pending
             at ./core/async_cancel.rs:219:13
  10: <deno_core::async_cancel::Cancelable<F> as core::future::future::Future>::poll
             at ./core/async_cancel.rs:66:12
  11: <deno_core::async_cancel::TryCancelable<F> as core::future::future::Future>::poll
             at ./core/async_cancel.rs:103:11
  12: deno_runtime::ops::http::op_http_request_next::{{closure}}
             at ./runtime/ops/http.rs:167:3
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  14: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/future/map.rs:55:37
  15: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/lib.rs:93:13
  16: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  17: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/future/map.rs:55:37
  18: <futures_util::future::future::Inspect<Fut,F> as core::future::future::Future>::poll
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/lib.rs:93:13
  19: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  20: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/stream/futures_unordered/mod.rs:521:17
  21: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/stream/stream/mod.rs:1416:9
  22: deno_core::runtime::JsRuntime::poll_pending_ops
             at ./core/runtime.rs:1283:23
  23: deno_core::runtime::JsRuntime::poll_event_loop
             at ./core/runtime.rs:620:29
  24: deno_runtime::worker::MainWorker::poll_event_loop
             at ./runtime/worker.rs:244:5
  25: deno_runtime::worker::MainWorker::run_event_loop::{{closure}}::{{closure}}
             at ./runtime/worker.rs:251:18
  26: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/poll_fn.rs:56:9
  27: deno_runtime::worker::MainWorker::run_event_loop::{{closure}}
             at ./runtime/worker.rs:251:5
  28: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  29: deno_runtime::worker::MainWorker::execute_module::{{closure}}::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/macros/select.rs:455:49
  30: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/future/poll_fn.rs:38:9
  31: deno_runtime::worker::MainWorker::execute_module::{{closure}}
             at ./runtime/worker.rs:209:5
  32: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  33: deno::run_command::{{closure}}
             at ./cli/main.rs:911:3
  34: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  35: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  36: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/task/local.rs:634:65
  37: tokio::coop::with_budget::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:106:9
  38: std::thread::local::LocalKey<T>::try_with
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  39: std::thread::local::LocalKey<T>::with
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  40: tokio::coop::with_budget
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:99:5
  41: tokio::coop::budget
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:76:5
  42: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/task/local.rs:634:42
  43: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/macros/scoped_tls.rs:61:9
  44: tokio::task::local::LocalSet::with
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/task/local.rs:548:9
  45: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/task/local.rs:624:9
  46: tokio::task::local::LocalSet::run_until::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/task/local.rs:498:9
  47: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  48: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  49: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/basic_scheduler.rs:213:62
  50: tokio::coop::with_budget::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:106:9
  51: std::thread::local::LocalKey<T>::try_with
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  52: std::thread::local::LocalKey<T>::with
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  53: tokio::coop::with_budget
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:99:5
  54: tokio::coop::budget
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/coop.rs:76:5
  55: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/basic_scheduler.rs:213:39
  56: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/basic_scheduler.rs:323:29
  57: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/macros/scoped_tls.rs:61:9
  58: tokio::runtime::basic_scheduler::enter
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/basic_scheduler.rs:323:5
  59: tokio::runtime::basic_scheduler::Inner<P>::block_on
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/basic_scheduler.rs:202:9
  60: tokio::runtime::basic_scheduler::InnerGuard<P>::block_on
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/basic_scheduler.rs:516:9
  61: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/basic_scheduler.rs:162:24
  62: tokio::runtime::Runtime::block_on
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/mod.rs:450:46
  63: tokio::task::local::LocalSet::block_on
             at /home/lucacasonato/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/task/local.rs:459:9
  64: deno::tokio_util::run_basic
             at ./cli/tokio_util.rs:24:3
  65: deno::main
             at ./cli/main.rs:1378:18
  66: core::ops::function::FnOnce::call_once
             at /home/lucacasonato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

**Comment by lucacasonato** [comment]
Nevermind, we tried to poll hyper after it has already returned `Poll::Ready`.
