### ISSUE TITLE
ConnectionRefused with many (5000) requests

### ISSUE THREAD

**Issue by lcmgh** [hyperium/hyper#3206]
My web frontend makes a lot of requests to my Axum based backend which proxies requests to another target. When it spawns around 5k requests  at once (don't ask why :)) the requests do fail in Chrome without any status code but with canceled. So I tried to reproduce this as code and found hyper is having trouble with this test when spawning 5k requests but not with 500. 

**Version**
`hyper = { version = "0.14.26", features = ["full"] }`

**Platform**
22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64

**Description**
Enter your issue details here.
One way to structure the description:

[short summary of the bug]

I tried this code:

```rust


pub mod test {
    use futures::{future::join_all, stream::select_all};
    use std::{time::Duration};

    use hyper_rustls::ConfigBuilderExt;
    use std::{convert::Infallible, error::Error, net::SocketAddr};
    use tower::BoxError;

    use hyper::{
        body::Bytes,
        service::{make_service_fn, service_fn},
        Body, Client, Request, Response, Server,
    };

    #[tokio::test]
    async fn many_requests() {
        tokio::spawn(async {
            // We'll bind to 127.0.0.1:3000
            let addr = SocketAddr::from(([127, 0, 0, 1], 3000));

            // A `Service` is needed for every connection, so this
            // creates one from our `hello_world` function.
            let make_svc = make_service_fn(|_conn| async {
                // service_fn converts our function into a `Service`
                Ok::<_, Infallible>(service_fn(echo))
            });

            let server = Server::bind(&addr).serve(make_svc);

            // Run this server for... forever!
            if let Err(e) = server.await {
                eprintln!("server error: {}", e);
            }
        });

        let tls = rustls::ClientConfig::builder()
            .with_safe_defaults()
            .with_native_roots()
            .with_no_client_auth();

        let https = hyper_rustls::HttpsConnectorBuilder::new()
            .with_tls_config(tls)
            .https_or_http()
            .enable_http1()
            .build();

       // Issue also occurs with:         let client = Client::new();
        let client = Client::builder()
            .pool_idle_timeout(Duration::from_secs(0))
            .pool_max_idle_per_host(0)
            .build::<_, hyper::Body>(https);

        let mut handles = vec![];
        for _ in 0..5000 {
            handles.push(client.get("http://localhost:3000/".try_into().unwrap()));
        }

        let responses = join_all(handles).await;
        for res in responses {
            let res = res.unwrap();
            assert_eq!(200, res.status());
        }
    }

    async fn echo(req: Request<Body>) -> Result<Response<Body>, BoxError> {
        Ok(Response::new(req.into_body()))
    }
}

```

I expected to see this happen: no errors

Instead, this happened: 
```
thread 'https::test::many_requests' panicked at 'called `Result::unwrap()` on an `Err` value: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }))', src/https.rs:115:27
```

**Comment by lcmgh** [comment]
When using http2 the error is

either
```
thread 'https::test::many_requests' panicked at 'called `Result::unwrap()` on an `Err` value: hyper::Error(ChannelClosed)'
```

or 

```
thread 'https::test::many_requests' panicked at 'called `Result::unwrap()` on an `Err` value: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }))', src/https.rs:112:27
```


http 2 client
```rust

let tls = rustls::ClientConfig::builder()
    .with_safe_defaults()
    .with_native_roots()
    .with_no_client_auth();

let https = hyper_rustls::HttpsConnectorBuilder::new()
    .with_tls_config(tls)
    .https_or_http()
    .enable_http2()
    .build();

let client = Client::builder()
    .pool_idle_timeout(Duration::from_secs(0))
    .pool_max_idle_per_host(0)
    .build::<_, hyper::Body>(https);
```

**Comment by seanmonstar** [comment]
`ConnectError("tcp connect error", Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })` is an error coming from the operating system.

When searching for "tcp connection refused", one of the reasons listed was:

> The port is open on the destination machine, but its backlog of pending connections is full.

**Comment by lcmgh** [comment]
Issue does not occur when changing the client to use http2 only without pool settings. 

```rust
        let client = Client::builder()
        .http2_only(true)
            // .pool_idle_timeout(Duration::from_secs(0))
            // .pool_max_idle_per_host(0)
            .build::<_, hyper::Body>(https);
```

This config does still cause the problem
```rust
        let client = Client::builder()
            // .pool_idle_timeout(Duration::from_secs(0))
            // .pool_max_idle_per_host(0)
            .build::<_, hyper::Body>(https);
```

**Comment by seanmonstar** [comment]
When you set http2_only, it will enforce a single connection to the remote. If you don't, it will open a new connection for each request.

Your server's TCP listener's backlog is full.
