### ISSUE TITLE
Simple request always fails on Mac OS X

### ISSUE THREAD

**Issue by wezm** [hyperium/hyper#508]
Given this small sample program basically copied from the README:

```rust
extern crate hyper;

use std::io::Read;

use hyper::Client;
use hyper::header::Connection;
use hyper::header::ConnectionOption;

fn main() {
    // Create a client.
    let mut client = Client::new();

    // Creating an outgoing request.
    let mut res = client.get("http://files.wezm.net/testpodcast.xml")
        // set a header
        .header(Connection(vec![ConnectionOption::Close]))
        // let 'er go!
        .send().unwrap();

    // Read the Response.
    let mut body = String::new();
    res.read_to_string(&mut body).unwrap();

    println!("Response: {}", body);
}
```

The request always fails with a HttpIoError (NotConnected): 

```
cargo run --verbose                                                                                                                                      Fresh typeable v0.1.1
       Fresh libc v0.1.6
       Fresh bitflags v0.1.1
       Fresh unicase v0.1.0
       Fresh traitobject v0.0.1
       Fresh lazy_static v0.1.10
       Fresh pkg-config v0.3.4
       Fresh gcc v0.3.5
       Fresh httparse v0.1.1
       Fresh rustc-serialize v0.3.14
       Fresh matches v0.1.2
       Fresh log v0.3.1
       Fresh num_cpus v0.2.4
       Fresh url v0.2.33
       Fresh mime v0.0.11
       Fresh openssl-sys v0.6.2
       Fresh time v0.1.25
       Fresh openssl v0.6.2
       Fresh cookie v0.1.20
       Fresh hyper v0.3.16
       Fresh request v0.1.0 (file:///Users/wmoore/Projects/Musicast/crawler/request)
     Running `target/debug/request`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: HttpIoError(Error { repr: Os(57) })', /Users/rustbuild/src/rust-buildbot/slave/beta-dist-rustc-mac/build/src/libcore/result.rs:729
Process didn't exit successfully: `target/debug/request` (exit code: 101)
```

This is with OS X 10.10.3 (14D136) and `rustc 1.0.0-beta.4 (850151a75 2015-04-30) (built 2015-04-30)`. The same program works when run on a Ubuntu 14.04 VM with the same version of rust.

It seems somewhat dependent on the URL, although more fail than don't. E.g. these work:

* http://www.itmedia.co.jp (albeit it fails later because the character set is Shift-JIS)
* http://bellroy.com/

These do not:

* http://google.com/
* http://feeds.feedburner.com/oneminutefrench
* http://files.wezm.net/testpodcast.xml
* http://www.marksherry.net/outburst_radio/outburst_radioshow_podcast.xml
* http://drclaw.net/feed/atom/

**Comment by reem** [comment]
Can you re-run with `RUST_BACKTRACE=1`, so we can get a backtrace for that panic?

**Comment by wezm** [comment]
Sure, doesn't look all that helpful though. I can tell you that it's the unwrap on send `.send().unwrap();` that is panicking though:

```
stack backtrace:
   1:        0x1050720df - sys::backtrace::write::h0f2fc53eb11eb814gWr
   2:        0x105075464 - panicking::on_panic::hd617a4042e8486fciUv
   3:        0x10506b245 - rt::unwind::begin_unwind_inner::hd84dfec22ac3667d1Bv
   4:        0x10506bad6 - rt::unwind::begin_unwind_fmt::h5bb6fa95bd57b24bFAv
   5:        0x105074d3c - rust_begin_unwind
   6:        0x1050949d5 - panicking::panic_fmt::hea516303ab7688d0lwy
   7:        0x104fad606 - result::Result<T, E>::unwrap::h5683422046223242116
   8:        0x104fad22c - main::ha0a39c096ced901bjaa
   9:        0x105076f88 - rust_try_inner
  10:        0x105076f75 - rust_try
  11:        0x105075c68 - rt::lang_start::h04063553a12d35edNOv
  12:        0x104fd7b1e - main
```

**Comment by seanmonstar** [comment]
Would you mind added env_logger (or similar) and collecting logs from
hyper? (with env_logger, you'd set RUST_LOG=hyper).

**Comment by wezm** [comment]
Sure, happy to help any way I can:

```
     Running `target/debug/request`
TRACE:hyper::client: send Get Url { scheme: "http", scheme_data: Relative(RelativeSchemeData { username: "", password: None, host: Domain("files.wezm.net"), port: None, default_port: Some(80), path: ["testpodcast.xml"] }), query: None, fragment: None }
TRACE:hyper::client: host="files.wezm.net"
TRACE:hyper::client: port=80
DEBUG:hyper::net: http scheme
DEBUG:hyper::client::request: request line: Get "/testpodcast.xml" Http11
DEBUG:hyper::client::request: headers=Headers { Connection: close, Host: files.wezm.net, }
TRACE:hyper::buffer: slicing (0, 1408, 4096)
TRACE:hyper::header: raw header: "Server"=[110, 103, 105, 110, 120, 47, 49, 46, 54, 46, 51]
TRACE:hyper::header: raw header: "Date"=[87, 101, 100, 44, 32, 48, 54, 32, 77, 97, 121, 32, 50, 48, 49, 53, 32, 48, 53, 58, 53, 48, 58, 51, 52, 32, 71, 77, 84]
TRACE:hyper::header: raw header: "Content-Type"=[116, 101, 120, 116, 47, 120, 109, 108]
TRACE:hyper::header: raw header: "Last-Modified"=[77, 111, 110, 44, 32, 49, 54, 32, 70, 101, 98, 32, 50, 48, 49, 53, 32, 48, 52, 58, 52, 51, 58, 48, 57, 32, 71, 77, 84]
TRACE:hyper::header: raw header: "X-Varnish"=[50, 57, 56, 52, 57, 51, 32, 50, 57, 56, 52, 57, 49]
TRACE:hyper::header: raw header: "Age"=[52, 51]
TRACE:hyper::header: raw header: "Via"=[49, 46, 49, 32, 118, 97, 114, 110, 105, 115, 104, 45, 118, 52]
TRACE:hyper::header: raw header: "Transfer-Encoding"=[99, 104, 117, 110, 107, 101, 100]
TRACE:hyper::header: raw header: "Connection"=[99, 108, 111, 115, 101]
TRACE:hyper::header: raw header: "Accept-Ranges"=[98, 121, 116, 101, 115]
DEBUG:hyper::client::response: version=Http11, status=Ok
DEBUG:hyper::client::response: headers=Headers { Transfer-Encoding: chunked, Via: 1.1 varnish-v4, Accept-Ranges: bytes, Date: Wed, 06 May 2015 05:50:34 GMT, Server: nginx/1.6.3, X-Varnish: 298493 298491, Age: 43, Content-Type: text/xml, Connection: close, Last-Modified: Mon, 16 Feb 2015 04:43:09 GMT, }
TRACE:hyper::client::pool: PooledStream.drop, is_closed=true, is_drained=false
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: HttpIoError(Error { repr: Os(57) })', /Users/rustbuild/src/rust-buildbot/slave/beta-dist-rustc-mac/build/src/libcore/result.rs:729
An unknown error occurred

To learn more, run the command again with --verbose.
```

**Comment by seanmonstar** [comment]
Hmm. Hyper is now calling shutdown because of the Connection: Close header.
After writing the end, it calls shutdown(Write). I wonder if there's a
difference in the way Mac and Linux handle libc::shutdown.

**Comment by seanmonstar** [comment]
@wezm If it's related to shutdown, this is the smallest case that would test it (I think...):

```rust
use std::io::{Read, Write};
use std::net;


fn main() {
    let mut stream = net::TcpStream::connect("rust-lang.org:80").unwrap();
    stream.write_all(b"GET / HTTP/1.1\r\nHost: rust-lang.org\r\n\r\n").unwrap();
    stream.shutdown(net::Shutdown::Write).unwrap();

    let mut s = String::new();
    stream.read_to_string(&mut s).unwrap();
    println!("{}", s);
}
```

**Comment by wezm** [comment]
For comparison here's the same thing run in the Linux VM:

```
     Running `target/debug/request`
TRACE:hyper::client: send Get Url { scheme: "http", scheme_data: Relative(RelativeSchemeData { username: "", password: None, host: Domain("files.wezm.net"), port: None, default_port: Some(80), path: ["testpodcast.xml"] }), query: None, fragment: None }
TRACE:hyper::client: host="files.wezm.net"
TRACE:hyper::client: port=80
DEBUG:hyper::net: http scheme
DEBUG:hyper::client::request: request line: Get "/testpodcast.xml" Http11
DEBUG:hyper::client::request: headers=Headers { Host: files.wezm.net, Connection: close, }
TRACE:hyper::buffer: slicing (0, 1408, 4096)
TRACE:hyper::header: raw header: "Server"=[110, 103, 105, 110, 120, 47, 49, 46, 54, 46, 51]
TRACE:hyper::header: raw header: "Date"=[87, 101, 100, 44, 32, 48, 54, 32, 77, 97, 121, 32, 50, 48, 49, 53, 32, 50, 51, 58, 48, 56, 58, 52, 54, 32, 71, 77, 84]
TRACE:hyper::header: raw header: "Content-Type"=[116, 101, 120, 116, 47, 120, 109, 108]
TRACE:hyper::header: raw header: "Last-Modified"=[77, 111, 110, 44, 32, 49, 54, 32, 70, 101, 98, 32, 50, 48, 49, 53, 32, 48, 52, 58, 52, 51, 58, 48, 57, 32, 71, 77, 84]
TRACE:hyper::header: raw header: "X-Varnish"=[52, 50, 57, 51, 48, 48, 32, 52, 50, 57, 50, 57, 56]
TRACE:hyper::header: raw header: "Age"=[52, 52]
TRACE:hyper::header: raw header: "Via"=[49, 46, 49, 32, 118, 97, 114, 110, 105, 115, 104, 45, 118, 52]
TRACE:hyper::header: raw header: "Transfer-Encoding"=[99, 104, 117, 110, 107, 101, 100]
TRACE:hyper::header: raw header: "Connection"=[99, 108, 111, 115, 101]
TRACE:hyper::header: raw header: "Accept-Ranges"=[98, 121, 116, 101, 115]
DEBUG:hyper::client::response: version=Http11, status=Ok
DEBUG:hyper::client::response: headers=Headers { Age: 44, Via: 1.1 varnish-v4, Last-Modified: Mon, 16 Feb 2015 04:43:09 GMT, Content-Type: text/xml, Transfer-Encoding: chunked, Server: nginx/1.6.3, Date: Wed, 06 May 2015 23:08:46 GMT, Accept-Ranges: bytes, Connection: close, X-Varnish: 429300 429298, }
TRACE:hyper::http: chunk size=6078
TRACE:hyper::http: Chunked read, remaining=6078
TRACE:hyper::http: Chunked read, remaining=6046
TRACE:hyper::http: Chunked read, remaining=5982
TRACE:hyper::http: Chunked read, remaining=5854
TRACE:hyper::http: Chunked read, remaining=5598
TRACE:hyper::http: Chunked read, remaining=5086
TRACE:hyper::http: Chunked read, remaining=4950
TRACE:hyper::http: Chunked read, remaining=4062
TRACE:hyper::http: Chunked read, remaining=2014
TRACE:hyper::http: Chunked read, remaining=854
TRACE:hyper::http: chunk size=0
TRACE:hyper::http: Chunked read, remaining=0
TRACE:hyper::http: end of chunked
Response: <?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" media="screen" href="/~d/styles/rss2full.xsl"?><?xml-stylesheet type="text/css" media="screen" href="http://feeds.feedburner.com/~d/styles/itemcontent.css"?><rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:cc="http://web.resource.org/cc/" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:media="http://search.yahoo.com/mrss/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:feedburner="http://rssnamespace.org/feedburner/ext/1.0" version="2.0">
  <channel>
    <title>Test Podcast</title>
  [snip]
  </channel>
</rss>

TRACE:hyper::client::pool: PooledStream.drop, is_closed=true, is_drained=false
```

**Comment by wezm** [comment]
The test case above works fine as posted. I tried adding a `Connection: close` header and it still works fine. :confused:

**Comment by seanmonstar** [comment]
@wezm what if you comment out the `Connection: close` header from the hyper example? If it still fails, we can look elsewhere.

**Comment by seanmonstar** [comment]
@wezm if it works without the Connection close, try the tcp example with your own url (don't forget to edit the `Host: ` part of the byte string.

**Comment by wezm** [comment]
Just read the man page for shutdown on [Linux](http://linux.die.net/man/2/shutdown) and [OS X](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man2/shutdown.2.html). From that point of view they should operate identically (of course the actual implementation may differ).

**Comment by wezm** [comment]
The hyper test case works when Connection close is removed. The TCP example when edited as follows also works, with and without the Connection close header.

```rust
    let mut stream = net::TcpStream::connect("files.wezm.net:80").unwrap();
    stream.write_all(b"GET /testpodcast.xml HTTP/1.1\r\nHost: files.wezm.net\r\n\r\n").unwrap();
```

**Comment by seanmonstar** [comment]
Hm, what if you change the tcp example to call shutdown twice?

```rust
// ...
stream.shutdown(net::Shutdown::Write).unwrap();
stream.shutdown(net::Shutdown::Write).unwrap();
// ...
```

**Comment by wezm** [comment]
Yup, panics with the same error as the original test case.

**Comment by seanmonstar** [comment]
Aha! So, seems Linux has no problem with that, but Mac does.

Hyper calls shutdown if there's Close header in the request. The response is also sending a Close header, and so shutdown is called a second time in the response. I assumed it'd be a no-op if it was already closed...

**Comment by wezm** [comment]
Cheers, thanks for your help and responsiveness.
