### ISSUE TITLE
hello.rs doesn't start on windows

### ISSUE THREAD

**Issue by stiv-yakovenko** [hyperium/hyper#818]
Here is what i get, port 3000 is not busy:

Listening on http://127.0.0.1:3000
thread '<unnamed>' panicked at 'You can't return Response::done() from Machine::create() until new release of slab crate. (requires insert_with_opt): Some(Error { repr: Os { code: 87, message: "The parameter is incorrect." } })', ../src/libcore\result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Any', ../src/libcore\result.rs:746
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
ERROR:hyper::server: listener accept error Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)
error: Process didn't exit successfully: `target\debug\rusttest.exe` (exit code: 101)

**Comment by stiv-yakovenko** [comment]
UPS, port was busy. Excuse me please.
